name: Deploy to Vercel

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Vercel
        uses: vercel/vercel-action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}       # Vercel token secret
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}     # Vercel org ID secret
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Vercel project ID secret
          prod: true                                      # Deploy to production
          # working-directory removed - using root directory